### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by sfsdfd62** [uci-cbcl/UFold#20]
My version information is as below:
cuDNN:8.5.0
cuda：11.7
pytorch=1.4.0
python=3.6.6
Ubuntu 20.04.4

**Comment by sfsdfd62** [comment]
> 

I understood this situation. This is because I'm using GTX 3090, which only supports CUDA version>11.0 and pytorch >some certain release. But it seems that Pytorch used in this work is way too out-dated, so we may need to upgrade it.

**Comment by sfsdfd62** [comment]
> Try torch.backends.cudnn.enabled = False, it resolves my problem, but the execution becomes very slow.

I understood this situation. This is because I'm using GTX 3090, which only supports CUDA version>11.0 and pytorch >some certain release. But it seems that Pytorch used in this work is way too out-dated, so we may need to upgrade it.
